# Generated by Django 4.2.7 on 2025-03-08 12:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HR_department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_department",
                    models.CharField(max_length=255, verbose_name="Название отдела HR"),
                ),
                (
                    "name_department_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название отдела HR"
                    ),
                ),
                (
                    "name_department_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название отдела HR"
                    ),
                ),
                (
                    "name_department_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название отдела HR"
                    ),
                ),
                (
                    "name_department_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название отдела HR"
                    ),
                ),
                (
                    "name_department_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название отдела HR"
                    ),
                ),
                (
                    "description_department",
                    models.CharField(max_length=255, verbose_name="Описание отдела HR"),
                ),
                (
                    "description_department_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Описание отдела HR"
                    ),
                ),
                (
                    "description_department_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Описание отдела HR"
                    ),
                ),
                (
                    "description_department_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Описание отдела HR"
                    ),
                ),
                (
                    "description_department_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Описание отдела HR"
                    ),
                ),
                (
                    "description_department_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Описание отдела HR"
                    ),
                ),
                (
                    "our_tasks_department",
                    ckeditor.fields.RichTextField(
                        verbose_name="Наши задачи в отделе HR"
                    ),
                ),
                (
                    "our_tasks_department_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Наши задачи в отделе HR"
                    ),
                ),
                (
                    "our_tasks_department_ky",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Наши задачи в отделе HR"
                    ),
                ),
                (
                    "our_tasks_department_tr",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Наши задачи в отделе HR"
                    ),
                ),
                (
                    "our_tasks_department_ar",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Наши задачи в отделе HR"
                    ),
                ),
                (
                    "our_tasks_department_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Наши задачи в отделе HR"
                    ),
                ),
                (
                    "head_department",
                    models.CharField(
                        max_length=255, verbose_name="Руководитель отдела HR"
                    ),
                ),
                (
                    "head_department_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Руководитель отдела HR"
                    ),
                ),
                (
                    "head_department_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Руководитель отдела HR"
                    ),
                ),
                (
                    "head_department_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Руководитель отдела HR"
                    ),
                ),
                (
                    "head_department_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Руководитель отдела HR"
                    ),
                ),
                (
                    "head_department_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Руководитель отдела HR"
                    ),
                ),
                (
                    "contacs_department",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_department_ru",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_department_ky",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_department_tr",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_department_ar",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_department_en",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "email_department",
                    models.EmailField(
                        default="Контакты для связи",
                        max_length=254,
                        verbose_name="Email отдела HR",
                    ),
                ),
                (
                    "phone_number_department",
                    models.CharField(
                        default="+7 (XXX) XXX-XX-XX",
                        max_length=255,
                        verbose_name="Номер телефона для связи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел HR",
                "verbose_name_plural": "Отделы HR",
            },
        ),
        migrations.CreateModel(
            name="Rector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_rector",
                    models.CharField(max_length=255, verbose_name="Имя ректора"),
                ),
                (
                    "name_rector_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя ректора"
                    ),
                ),
                (
                    "name_rector_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя ректора"
                    ),
                ),
                (
                    "name_rector_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя ректора"
                    ),
                ),
                (
                    "name_rector_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя ректора"
                    ),
                ),
                (
                    "name_rector_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Имя ректора"
                    ),
                ),
                (
                    "job_title_rector",
                    models.CharField(max_length=255, verbose_name="Должность ректора"),
                ),
                (
                    "job_title_rector_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность ректора"
                    ),
                ),
                (
                    "job_title_rector_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность ректора"
                    ),
                ),
                (
                    "job_title_rector_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность ректора"
                    ),
                ),
                (
                    "job_title_rector_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность ректора"
                    ),
                ),
                (
                    "job_title_rector_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Должность ректора"
                    ),
                ),
                (
                    "education_rector",
                    models.CharField(
                        max_length=255,
                        verbose_name="Образование ректора(Доктор Гумонитарных Наук)",
                    ),
                ),
                (
                    "education_rector_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Образование ректора(Доктор Гумонитарных Наук)",
                    ),
                ),
                (
                    "education_rector_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Образование ректора(Доктор Гумонитарных Наук)",
                    ),
                ),
                (
                    "education_rector_tr",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Образование ректора(Доктор Гумонитарных Наук)",
                    ),
                ),
                (
                    "education_rector_ar",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Образование ректора(Доктор Гумонитарных Наук)",
                    ),
                ),
                (
                    "education_rector_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Образование ректора(Доктор Гумонитарных Наук)",
                    ),
                ),
                (
                    "image_rector",
                    models.ImageField(upload_to="rector/", verbose_name="Фото ректора"),
                ),
            ],
            options={
                "verbose_name": "Ректор",
                "verbose_name_plural": "Ректоры",
            },
        ),
        migrations.CreateModel(
            name="ScientWorksRector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_works",
                    models.CharField(
                        max_length=255, verbose_name="Описание научного труда ректора"
                    ),
                ),
                (
                    "description_works_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание научного труда ректора",
                    ),
                ),
                (
                    "description_works_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание научного труда ректора",
                    ),
                ),
                (
                    "description_works_tr",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание научного труда ректора",
                    ),
                ),
                (
                    "description_works_ar",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание научного труда ректора",
                    ),
                ),
                (
                    "description_works_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание научного труда ректора",
                    ),
                ),
                (
                    "date_works",
                    models.CharField(
                        max_length=255, verbose_name="Дата публикации научного труда"
                    ),
                ),
                (
                    "date_works_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации научного труда",
                    ),
                ),
                (
                    "date_works_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации научного труда",
                    ),
                ),
                (
                    "date_works_tr",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации научного труда",
                    ),
                ),
                (
                    "date_works_ar",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации научного труда",
                    ),
                ),
                (
                    "date_works_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации научного труда",
                    ),
                ),
                (
                    "major_works",
                    ckeditor.fields.RichTextField(
                        verbose_name="Основные работы ректора"
                    ),
                ),
                (
                    "major_works_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Основные работы ректора"
                    ),
                ),
                (
                    "major_works_ky",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Основные работы ректора"
                    ),
                ),
                (
                    "major_works_tr",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Основные работы ректора"
                    ),
                ),
                (
                    "major_works_ar",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Основные работы ректора"
                    ),
                ),
                (
                    "major_works_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Основные работы ректора"
                    ),
                ),
                (
                    "link_pdf_works",
                    models.URLField(verbose_name="Ссылка на PDF-версию научного труда"),
                ),
                (
                    "contacs_works",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        verbose_name="Контакты для связи",
                    ),
                ),
                (
                    "contacs_works_ru",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты для связи",
                    ),
                ),
                (
                    "contacs_works_ky",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты для связи",
                    ),
                ),
                (
                    "contacs_works_tr",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты для связи",
                    ),
                ),
                (
                    "contacs_works_ar",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты для связи",
                    ),
                ),
                (
                    "contacs_works_en",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты для связи",
                    ),
                ),
                (
                    "email_works",
                    models.EmailField(
                        default="Контакты для связи",
                        max_length=254,
                        verbose_name="Email для связи",
                    ),
                ),
                (
                    "phone_number_works",
                    models.CharField(
                        default="+7 (XXX) XXX-XX-XX",
                        max_length=255,
                        verbose_name="Номер телефона для связи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Научные труды ректора",
                "verbose_name_plural": "Научные труды ректора",
            },
        ),
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_vacancy",
                    models.CharField(max_length=255, verbose_name="Название вакансии"),
                ),
                (
                    "name_vacancy_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "name_vacancy_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "name_vacancy_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "name_vacancy_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "name_vacancy_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "responsibilities_vacancy",
                    models.CharField(
                        max_length=255, verbose_name="Обязанности вакансии"
                    ),
                ),
                (
                    "responsibilities_vacancy_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Обязанности вакансии"
                    ),
                ),
                (
                    "responsibilities_vacancy_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Обязанности вакансии"
                    ),
                ),
                (
                    "responsibilities_vacancy_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Обязанности вакансии"
                    ),
                ),
                (
                    "responsibilities_vacancy_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Обязанности вакансии"
                    ),
                ),
                (
                    "responsibilities_vacancy_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Обязанности вакансии"
                    ),
                ),
                (
                    "date_vacancy",
                    models.CharField(
                        max_length=255, verbose_name="Дата публикации вакансии"
                    ),
                ),
                (
                    "date_vacancy_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации вакансии",
                    ),
                ),
                (
                    "date_vacancy_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации вакансии",
                    ),
                ),
                (
                    "date_vacancy_tr",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации вакансии",
                    ),
                ),
                (
                    "date_vacancy_ar",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации вакансии",
                    ),
                ),
                (
                    "date_vacancy_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Дата публикации вакансии",
                    ),
                ),
                (
                    "teacher_islamic_sciences_vacancy",
                    ckeditor.fields.RichTextField(
                        verbose_name="Преподаватель исламских наук"
                    ),
                ),
                (
                    "teacher_islamic_sciences_vacancy_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Преподаватель исламских наук"
                    ),
                ),
                (
                    "teacher_islamic_sciences_vacancy_ky",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Преподаватель исламских наук"
                    ),
                ),
                (
                    "teacher_islamic_sciences_vacancy_tr",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Преподаватель исламских наук"
                    ),
                ),
                (
                    "teacher_islamic_sciences_vacancy_ar",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Преподаватель исламских наук"
                    ),
                ),
                (
                    "teacher_islamic_sciences_vacancy_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Преподаватель исламских наук"
                    ),
                ),
                (
                    "contacs_vacancy",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_vacancy_ru",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_vacancy_ky",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_vacancy_tr",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_vacancy_ar",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "contacs_vacancy_en",
                    models.CharField(
                        default="Контакты для связи",
                        max_length=255,
                        null=True,
                        verbose_name="Контакты отдела HR",
                    ),
                ),
                (
                    "email_vacancy",
                    models.EmailField(
                        default="Контакты для связи",
                        max_length=254,
                        verbose_name="Email отдела HR",
                    ),
                ),
                (
                    "phone_number_vacancy",
                    models.CharField(
                        default="+7 (XXX) XXX-XX-XX",
                        max_length=255,
                        verbose_name="Номер телефона для связи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.CreateModel(
            name="VacanciesObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_vacancy",
                    models.CharField(max_length=255, verbose_name="Заголовок объекта"),
                ),
                (
                    "title_vacancy_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_vacancy_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_vacancy_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_vacancy_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_vacancy_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.vacancies",
                        verbose_name="вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объекты вакансий",
                "verbose_name_plural": "Объекты вакансий",
            },
        ),
        migrations.CreateModel(
            name="ScientWorksRectorObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_works",
                    models.CharField(max_length=255, verbose_name="Заголовок объекта"),
                ),
                (
                    "title_works_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_works_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_works_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_works_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_works_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "scientworks_rector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.scientworksrector",
                        verbose_name="научные труды ректора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объекты научных трудов ректора",
                "verbose_name_plural": "Объекты научных трудов ректора",
            },
        ),
        migrations.CreateModel(
            name="RectorObjectsTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок объекта"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок объекта"
                    ),
                ),
                (
                    "rector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.rector",
                        verbose_name="rector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект ректора",
                "verbose_name_plural": "Объекты ректора",
            },
        ),
        migrations.CreateModel(
            name="HR_departmentObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_department",
                    models.CharField(
                        blank=True,
                        default="Объект для вакансии",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок объекта",
                    ),
                ),
                (
                    "title_department_ru",
                    models.CharField(
                        blank=True,
                        default="Объект для вакансии",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок объекта",
                    ),
                ),
                (
                    "title_department_ky",
                    models.CharField(
                        blank=True,
                        default="Объект для вакансии",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок объекта",
                    ),
                ),
                (
                    "title_department_tr",
                    models.CharField(
                        blank=True,
                        default="Объект для вакансии",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок объекта",
                    ),
                ),
                (
                    "title_department_ar",
                    models.CharField(
                        blank=True,
                        default="Объект для вакансии",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок объекта",
                    ),
                ),
                (
                    "title_department_en",
                    models.CharField(
                        blank=True,
                        default="Объект для вакансии",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок объекта",
                    ),
                ),
                (
                    "hr_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.hr_department",
                        verbose_name="отдел HR",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объекты вакансий отдела HR",
                "verbose_name_plural": "Объекты вакансий отдела HR",
            },
        ),
    ]
