# Generated by Django 4.2.7 on 2025-03-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listpagesobject',
            old_name='title',
            new_name='two_title',
        ),
        migrations.RenameField(
            model_name='listpagesobject',
            old_name='title_en',
            new_name='two_title_ar',
        ),
        migrations.RenameField(
            model_name='listpagesobject',
            old_name='title_ar',
            new_name='two_title_en',
        ),
        migrations.RenameField(
            model_name='listpagesobject',
            old_name='title_ky',
            new_name='two_title_ky',
        ),
        migrations.RenameField(
            model_name='listpagesobject',
            old_name='title_ru',
            new_name='two_title_ru',
        ),
        migrations.RenameField(
            model_name='listpagesobject',
            old_name='title_tr',
            new_name='two_title_tr',
        ),
    ]
