# Generated by Django 4.2.7 on 2025-03-08 12:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=255, verbose_name="Дата")),
                (
                    "date_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_ky",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_tr",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_ar",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_en",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "awarded",
                    models.CharField(max_length=255, verbose_name="Присуждается"),
                ),
                (
                    "awarded_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                ("achieve", ckeditor.fields.RichTextField(verbose_name="Достижение")),
                (
                    "achieve_ru",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_ky",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_tr",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_ar",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_en",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Место")),
                (
                    "location_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_ky",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_tr",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_ar",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_en",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Progress/", verbose_name="Фото Достижения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Все Достижения",
                "verbose_name_plural": "Все Достижения",
            },
        ),
        migrations.CreateModel(
            name="Educational",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("date", models.CharField(max_length=255, verbose_name="Дата")),
                (
                    "date_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_ky",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_tr",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_ar",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "date_en",
                    models.CharField(max_length=255, null=True, verbose_name="Дата"),
                ),
                (
                    "awarded",
                    models.CharField(max_length=255, verbose_name="Присуждается"),
                ),
                (
                    "awarded_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                (
                    "awarded_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Присуждается"
                    ),
                ),
                ("achieve", ckeditor.fields.RichTextField(verbose_name="Достижение")),
                (
                    "achieve_ru",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_ky",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_tr",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_ar",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                (
                    "achieve_en",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Достижение"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Место")),
                (
                    "location_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_ky",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_tr",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_ar",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "location_en",
                    models.CharField(max_length=255, null=True, verbose_name="Место"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Progress/", verbose_name="Фото Достижения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Воспитание",
                "verbose_name_plural": "Воспитание",
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_tr",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "description_ru",
                    ckeditor.fields.RichTextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_ky",
                    ckeditor.fields.RichTextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_tr",
                    ckeditor.fields.RichTextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_ar",
                    ckeditor.fields.RichTextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
    ]
