# Generated by Django 4.2.7 on 2025-03-01 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_tr', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ar', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Активные Студенты',
                'verbose_name_plural': 'Активные Студенты',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок страницы')),
                ('title_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок страницы')),
                ('title_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок страницы')),
                ('title_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок страницы')),
                ('title_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок страницы')),
                ('title_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок страницы')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание страницы')),
                ('accommodation_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для условий проживания')),
                ('accommodation_text', ckeditor.fields.RichTextField(verbose_name='Описание условий проживания')),
                ('spiritual_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для духовной атмосферы')),
                ('spiritual_text', ckeditor.fields.RichTextField(verbose_name='Описание духовной атмосферы')),
                ('security_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для безопасности и порядка')),
                ('security_text', ckeditor.fields.RichTextField(verbose_name='Описание безопасности и порядка')),
                ('student_life_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для студенческого быта')),
                ('student_life_text', ckeditor.fields.RichTextField(verbose_name='Описание студенческого быта')),
                ('reviews_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для отзывов студентов')),
                ('reviews_text', ckeditor.fields.RichTextField(verbose_name='Описание отзывов студентов')),
                ('images', models.ImageField(blank=True, null=True, upload_to='hostel_photos/', verbose_name='Фотографии общежития')),
            ],
            options={
                'verbose_name': 'Студенческое общежитие',
                'verbose_name_plural': 'Студенческое общежитие',
            },
        ),
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_tr', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ar', ckeditor.fields.RichTextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Студенчекий Парламент',
                'verbose_name_plural': 'Студенчекий Парламент',
            },
        ),
        migrations.CreateModel(
            name='StudentLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок страницы')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание страницы')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы')),
                ('education_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для образования и науки')),
                ('education_text', ckeditor.fields.RichTextField(verbose_name='Описание для образования и науки')),
                ('spiritual_development_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для духовного развития')),
                ('spiritual_development_text', ckeditor.fields.RichTextField(verbose_name='Описание духовного развития')),
                ('cultural_events_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для культурных и общественных мероприятий')),
                ('cultural_events_text', ckeditor.fields.RichTextField(verbose_name='Описание культурных и общественных мероприятий')),
                ('sports_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для спорта и здорового образа жизни')),
                ('sports_text', ckeditor.fields.RichTextField(verbose_name='Описание спорта и здорового образа жизни')),
                ('reviews_title', ckeditor.fields.RichTextField(verbose_name='Заголовок для отзывов студентов')),
                ('reviews_text', ckeditor.fields.RichTextField(verbose_name='Описание отзывов студентов')),
                ('images', models.ImageField(blank=True, null=True, upload_to='student_life_photos/', verbose_name='Фотографии студенческой жизни')),
            ],
            options={
                'verbose_name': 'Студенческая жизнь в академии',
                'verbose_name_plural': 'Студенческая жизнь в академии',
            },
        ),
    ]
