# Generated by Django 4.2.7 on 2025-03-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Getrequest', '0004_rename_active_count_visit_count1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='active_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='inactive_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
