# Generated by Django 4.2.7 on 2025-04-09 07:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголловок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Заголловок')),
            ],
            options={
                'verbose_name': 'Заголовки Журналов',
                'verbose_name_plural': 'Заголовки Журналов',
            },
        ),
        migrations.CreateModel(
            name='NewsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголловок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Заголловок')),
            ],
            options={
                'verbose_name': 'Заголовки новостей',
                'verbose_name_plural': 'Заголовки новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=155, verbose_name='Заголловок')),
                ('title', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField(verbose_name='Заголловок')),
                ('image', models.ImageField(upload_to='cards/', verbose_name='Заголловок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mainpage.newsmain')),
            ],
            options={
                'verbose_name': 'новостей',
                'verbose_name_plural': 'новостей',
            },
        ),
        migrations.CreateModel(
            name='MagazineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=155, verbose_name='Заголловок')),
                ('title', models.CharField(max_length=255, verbose_name='Заголловок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Заголловок')),
                ('image', models.ImageField(upload_to='missions/', verbose_name='Заголловок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mainpage.magazine')),
            ],
            options={
                'verbose_name': 'Журналов',
                'verbose_name_plural': 'Журналов',
            },
        ),
    ]
