# Generated by Django 4.2.7 on 2025-04-09 08:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_magazine_newsmain_newscard_magazinecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='description_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='text_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='text_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='magazinecard',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newscard',
            name='text_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newscard',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newscard',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newscard',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newscard',
            name='text_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newscard',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscard',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscard',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscard',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscard',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='description_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
        migrations.AddField(
            model_name='newsmain',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголловок'),
        ),
    ]
