# Generated by Django 4.2.7 on 2025-02-22 03:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Учёный совет')),
                ('title_ru', models.CharField(max_length=225, null=True, verbose_name='Учёный совет')),
                ('title_ky', models.CharField(max_length=225, null=True, verbose_name='Учёный совет')),
                ('title_en', models.CharField(max_length=225, null=True, verbose_name='Учёный совет')),
                ('title_tr', models.CharField(max_length=225, null=True, verbose_name='Учёный совет')),
                ('title_ar', models.CharField(max_length=225, null=True, verbose_name='Учёный совет')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Учёный совет',
                'verbose_name_plural': 'Учёные советы',
            },
        ),
        migrations.CreateModel(
            name='CenterEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Центр образования')),
                ('title_ru', models.CharField(max_length=225, null=True, verbose_name='Центр образования')),
                ('title_ky', models.CharField(max_length=225, null=True, verbose_name='Центр образования')),
                ('title_en', models.CharField(max_length=225, null=True, verbose_name='Центр образования')),
                ('title_tr', models.CharField(max_length=225, null=True, verbose_name='Центр образования')),
                ('title_ar', models.CharField(max_length=225, null=True, verbose_name='Центр образования')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Центр образования',
                'verbose_name_plural': 'Центры образования',
            },
        ),
        migrations.CreateModel(
            name='ScientificJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Издание научных журналов')),
                ('title_ru', models.CharField(max_length=225, null=True, verbose_name='Издание научных журналов')),
                ('title_ky', models.CharField(max_length=225, null=True, verbose_name='Издание научных журналов')),
                ('title_en', models.CharField(max_length=225, null=True, verbose_name='Издание научных журналов')),
                ('title_tr', models.CharField(max_length=225, null=True, verbose_name='Издание научных журналов')),
                ('title_ar', models.CharField(max_length=225, null=True, verbose_name='Издание научных журналов')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scientific')),
                ('link', models.URLField(verbose_name='Ссылка на журнал')),
            ],
            options={
                'verbose_name': 'Издание научных журналов',
                'verbose_name_plural': 'Издания научных журналов',
            },
        ),
    ]
